### PR TITLE
add ScriptModule, mostly intended to be used as a base for custom modules

### PR DESCRIPTION
**Pull request by monsieurgustav**
This is a 1st useful step to build "script heavy" custom modules.

### CODE REVIEW

**Review by benkuper — COMMENTED** [review]
I think the naming can bring some confusion, as it doesn't require a script, or generate one.
"Empty Module" or "Base", "Dommy" ? 
Let's find a good name for it

**Comment by monsieurgustav** [comment]
I started with "empty" but renamed it.
Maybe "base" is better: it's intended to script developers, base means something for them at least. But it might be confusing for others though.

That's the reason I chose script in the end: it makes clear that it's only useful for script (development) so the regular user can just ignore it.
"script base" maybe?

**Comment by benkuper** [comment]
I'd rather not have "script" in the name, I understand it's mainly to attach a script, but the module itself doesn't require nor contain any script to be "functional". Also, it could just be a holder for some values or testing whatever, or could maybe have other non script uses in the future.

**Comment by monsieurgustav** [comment]
"container" then?

**Comment by benkuper** [comment]
will be soon taken for the state machine ;)
Interesting > 
https://www.merriam-webster.com/thesaurus/empty#:~:text=Some%20common%20synonyms%20of%20empty,a%20complete%20absence%20of%20contents.

Vacant Module could work but it feels not so vacant at the same time ahah

**Comment by benkuper** [comment]
I think empty remains the most explicit one

**Comment by monsieurgustav** [comment]
OK!
What about the category now?  :)

I put it in "System" at first, but it doesn't really fit there.
"Utility" ?

"Utility/Empty" gives a sense of emptiness :)

**Comment by benkuper** [comment]
ahah :)
Actually I would put it in no menu, directly at the top (if it's possible at all ?? I think yes). Otherwise, "Custom" would me my choice

**Review by benkuper — COMMENTED** [review]
Can you try removing the "Custom" menu, just "" ?

**Comment by monsieurgustav** [comment]
I renamed to EmptyModule and put it in the "Custom" category.

Having no category works, but it adds the item at the top of the menu, which feels weird for a mostly useless module.
Custom makes much more sense.
I also added the icon used by the example custom module, that looks like this : </>.

**Comment by benkuper** [comment]
Ok I'll merge it like that then :)
Thank you !

**Review by benkuper — APPROVED** [review]

**Pull request merged**
